# Generated by Django 4.0.4 on 2022-04-12 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flight', '0002_person_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='destination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='flight.airport'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='flight',
            name='start',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hey', to='flight.airport'),
        ),
    ]
